version: "3.9"
services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  auth-service:
    build:
      context: src/AuthService.Api
      dockerfile: Dockerfile
    ports:
      - "8080:80" # for debugging
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=80"
      - "traefik.http.middlewares.simple-auth.forwardauth.address=http://auth-service/auth/forward-auth"
      - "traefik.http.middlewares.simple-auth.forwardauth.authResponseHeaders=X-User-Id, X-User-Roles" # forwarded to the downstream service
    depends_on:
      - traefik
  item-service:
    build:
      context: src/ItemService.Api
      dockerfile: Dockerfile
    ports:
      - "8081:80" # for debugging
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.item-service.rule=Host(`localhost`) && PathPrefix(`/items`)"
      - "traefik.http.routers.item-service.entrypoints=web"
      - "traefik.http.services.item-service.loadbalancer.server.port=80"
      - "traefik.http.routers.item-service.middlewares=simple-auth"
    depends_on:
      - traefik
  recommendation-service:
    build:
      context: src/RecommendationService.Api
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - item-service
      - traefik
    # labels:
      # - "traefik.enable=true"
      
